<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Vorken.RemoteAdmin</AssemblyName>
    <RootNamespace>Vorken.RemoteAdmin</RootNamespace>
    <Version>1.1.0</Version>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Title>Vorken Administração Remota</Title>
    <Product>Vorken Remote Support</Product>
    <Company>Vorken</Company>
    <Authors>Vorken</Authors>
    <RepositoryUrl>https://github.com/kaiquedupix-max/vorkenAc</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Copyright>Copyright © Vorken 2026. Todos os direitos reservados.</Copyright>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
    <FileVersion>1.1.0.0</FileVersion>
    <InformationalVersion>1.1.0</InformationalVersion>
    <ApplicationIcon>..\agent\assets\vorken.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>
</Project>
